server:
  port: ${EUREKA_APP_PORT:8761}

spring:
  application:
    name: eureka-server-app

eureka:
  instance:
    hostname: eureka-server-app
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone : http://eureka-server-app:8761/eureka/



